### ISSUE TITLE
64 bit build

### ISSUE THREAD

**Issue by Frozenfire92** [ScruffyFurn/LongBoat#2]
In the releases the dlls are only 32 bit. which causes errors in the 64 bit version of unity (which I think will be default for most people). I was able to build 64 bit with VS 2015 with no issues and this fixed the errors within unity.

![image](https://cloud.githubusercontent.com/assets/5893112/9482767/00fd43e6-4b6e-11e5-9006-48e38a2c9f30.png)

**Comment by Xenetics** [comment]
Thanks for catching this oversight. I will correct this issue immediately.
